"""cria tabelas de clientes, rpas e chaves jwt

Revision ID: a369a9e66d98
Revises:
Create Date: 2026-08-12 00:32:30.584160

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a369a9e66d98"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chaves_jwt",
        sa.Column("kid", sa.String(length=64), nullable=False),
        sa.Column("chave_publica_pem", sa.String(length=4096), nullable=False),
        sa.Column("algoritmo", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("kid"),
    )
    op.create_index(op.f("ix_chaves_jwt_status"), "chaves_jwt", ["status"], unique=False)
    op.create_index(
        "ix_chaves_jwt_unica_ativa",
        "chaves_jwt",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'ativa'"),
    )
    op.create_table(
        "clientes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.String(length=120), nullable=False),
        sa.Column("client_secret_hash", sa.String(length=255), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("descricao", sa.String(length=500), nullable=True),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("secret_rotacionado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revogado_em", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clientes_client_id"), "clientes", ["client_id"], unique=True)
    op.create_index(op.f("ix_clientes_status"), "clientes", ["status"], unique=False)
    op.create_index(op.f("ix_clientes_tipo"), "clientes", ["tipo"], unique=False)
    op.create_table(
        "rpas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rpa_id", sa.String(length=120), nullable=False),
        sa.Column("nome", sa.String(length=150), nullable=False),
        sa.Column("descricao", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revogado_em", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rpas_rpa_id"), "rpas", ["rpa_id"], unique=True)
    op.create_index(op.f("ix_rpas_status"), "rpas", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rpas_status"), table_name="rpas")
    op.drop_index(op.f("ix_rpas_rpa_id"), table_name="rpas")
    op.drop_table("rpas")
    op.drop_index(op.f("ix_clientes_tipo"), table_name="clientes")
    op.drop_index(op.f("ix_clientes_status"), table_name="clientes")
    op.drop_index(op.f("ix_clientes_client_id"), table_name="clientes")
    op.drop_table("clientes")
    op.drop_index(
        "ix_chaves_jwt_unica_ativa",
        table_name="chaves_jwt",
        postgresql_where=sa.text("status = 'ativa'"),
    )
    op.drop_index(op.f("ix_chaves_jwt_status"), table_name="chaves_jwt")
    op.drop_table("chaves_jwt")
    # ### end Alembic commands ###
